#Python database connectivity -
# we require three things - 1 Mysql - Open source database management system
#2 - Connector to driver- connecter is program that establish connection between python program and mysql database.
#3 - python

#cmd - mysql -u root -p
#idle - help("modules")
#install connector - or
#idle - import mysql  to check error
#cmd - 1 pip, 2 pip --version 3 - python -m pip install mysql-connector-python



#connectiong mysql and python
#1 - import mysql.connector  mysql - module, connector is a submodule
#2 - connect() function
#3 -


#ex -1
import mysql.connector
print("Mysql connector is installed")
'''
mysql.connector.connect(
    user = 'root',
    password = "12345",
    host = 'localhost',
    port = 3306
)
print("connected")

'''
'''
#ex-2 with exception handling
try:
    mysql.connector.connect(
        user='root',
        password="12345",
        host='localhost',
        port=3306
    )
except Exception as obj:
    print("can not connect")
else:
    print("connected")

'''
#3 - how to check connection status and close them  - is_connected() method
'''
try:
    conn = mysql.connector.connect(
        user='root',
        password="12345",
        host='localhost',
        port=3306
    )
    if conn.is_connected():
        print("Connected")
except Exception as obj:
    print("can not connect")

conn.close()
'''
#4 - cursor object - it allow python code to execute sql command in a databse session
#syntax - conn.cursor()
# -execute query - cursor_object.execute(Query, param = None)

'''
try:
    conn= mysql.connector.connect(
        user='root',
        password="12345",
        host='localhost',
        port=3306
    )
    if conn.is_connected():
        print("Connected")
except Exception as obj:
    print("can not connect")

cur = conn.cursor()
cur.execute("Create database code")
cur.close()
conn.close()

'''
''''
#create query with python script
try:
    conn= mysql.connector.connect(
        user='root',
        password="12345",
        host='localhost',
        port=3306
    )
    if conn.is_connected():
        print("Connected")
except Exception as obj:
    print("can not connect")

cur = conn.cursor()
cur.execute("use code")
cur.execute("""create table Person(
Name varchar(50),
Last_name varchar(20),
language varchar(50)
)""")
cur.close()




conn.close()

#insert data in table
try:
    con = mysql.connector.connect(
        user = 'root',
        password ='12345',
        host = 'localhost',
        port = 3306,
        database = 'code'
    )
    if con.is_connected():
        print('connected')
except Exception as e:
    print("can not connect")

cur = con.cursor()
sql = "Insert into person(Name, last_name, language) values('Raj', 'Sharma', 'English'),('sagar', 'verma', 'Hindi')"
cur.execute(sql)
con.commit()
cur.close()
con.close()

#update and delete table
import mysql.connector as mysql
try:
    db = mysql.connect(
        user='root',
        password='12345',
        host='localhost',
        port=3306,
        database='code'
    )
    if db.is_connected():
        print('connected')
except Exception as e:
    print("can not connect")


cur = db.cursor()
sql = "update person set Name = 'Ram' where language = 'English'"
sql1 = "delete from person where Name = 'sagar'"
try:
  cur.execute(sql)
  db.commit()
  print(f"{cur.rowcount} are uddated")
  cur.execute(sql1)
  db.commit()
except:
  db.rollback()
  print("something went wrong")
cur.close()
db.close()

'''
#fetch data from mysql - felch all data generated by select query
import mysql.connector as mysql
try:
    db = mysql.connect(
        user='root',
        password='12345',
        host='localhost',
        port=3306,
        database='code'
    )
    if db.is_connected():
        print('connected')
except Exception as e:
    print("can not connect")


cur = db.cursor()
sql = "select * from Person"
cur.execute(sql)
data = cur.fetchone()
print(data)
for ele in data:
    print(ele)

cur.close()
db.close()





























































